version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: devfolio_local_django
    container_name: django
    stdin_open: true
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    environment:
      # Set these in the CI environment
      # https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DATABASE_URL
      - USE_DOCKER
    ports:
      - "9001:8000"
    command: /start
    networks:
      - backend

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: devfolio_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      # Set these in the CI environment
      # https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "8433:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
