# Generated by Django 3.1.13 on 2021-08-18 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
                ('featured_image', models.ImageField(blank=True, upload_to='images', verbose_name='Featured Image')),
                ('resume', models.FileField(blank=True, upload_to='resume', verbose_name='Resume')),
                ('usp_main_image', models.ImageField(blank=True, upload_to='images', verbose_name='Unique Selling Points - Main Image')),
                ('usp1_title', models.CharField(blank=True, max_length=30, verbose_name='Unique Selling Point 1 - Title')),
                ('usp1_description', models.TextField(blank=True, max_length=300, verbose_name='Unique Selling Point 1 - Description')),
                ('usp1_image', models.FileField(blank=True, upload_to='images', verbose_name='Unique Selling Point 1 - Image')),
                ('usp2_title', models.CharField(blank=True, max_length=30, verbose_name='Unique Selling Point 2 - Title')),
                ('usp2_description', models.TextField(blank=True, max_length=300, verbose_name='Unique Selling Point 2 - Description')),
                ('usp2_image', models.FileField(blank=True, upload_to='images', verbose_name='Unique Selling Point 2 - Image')),
                ('usp3_title', models.CharField(blank=True, max_length=30, verbose_name='Unique Selling Point 3 - Title')),
                ('usp3_description', models.TextField(blank=True, max_length=300, verbose_name='Unique Selling Point 3 - Description')),
                ('usp3_image', models.FileField(blank=True, upload_to='images', verbose_name='Unique Selling Point 3 - Image')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
                ('featured_image', models.ImageField(upload_to='images', verbose_name='Featured Image')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('client', models.CharField(blank=True, max_length=50, verbose_name='Client')),
                ('services', models.CharField(blank=True, max_length=100, verbose_name='Services')),
                ('client_url', models.URLField(blank=True, verbose_name='Client URL')),
                ('live_url', models.URLField(blank=True, verbose_name='Live URL')),
                ('repo_url', models.URLField(blank=True, verbose_name='Repo URL')),
                ('objective_text', models.TextField(blank=True, max_length=500, verbose_name='Objective')),
                ('tools_n_tech_text', models.TextField(blank=True, max_length=500, verbose_name='Tools and Tech')),
                ('challenge_text', models.TextField(blank=True, max_length=500, verbose_name='Challenge')),
                ('share_fb', models.BooleanField(default=False, verbose_name='Share on FaceBook')),
                ('share_twitter', models.BooleanField(default=False, verbose_name='Share on Twitter')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='VideoURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Caption')),
                ('url', models.URLField(verbose_name='Video URL')),
                ('screenshot', models.ImageField(upload_to='screenshots', verbose_name='Screenshot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'VideoURL',
                'verbose_name_plural': 'VideoURLs',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Title')),
                ('project', models.ManyToManyField(to='portfolio.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, verbose_name='Caption')),
                ('screenshot', models.ImageField(upload_to='screenshots', verbose_name='Screenshot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
            },
        ),
    ]
