# Generated by Django 3.1.13 on 2021-08-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='frontpage_greeting',
            field=models.CharField(blank=True, max_length=50, verbose_name='Frontpage Greeting'),
        ),
    ]
