# Generated by Django 3.1.13 on 2021-08-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_frontpage_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url_message_modal_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Live URL Popup Message'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url_message_modal_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Live URL Popup Title'),
        ),
    ]
