name: Django CI

env:
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
#   DOCKER_BUILDKIT: 1
#   COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Docker Compose Action
      # You may pin to the exact commit or the version.
      # uses: isbang/compose-action@fab6f72bef82b75de541a7b9da1d23412953c2bd
      uses: isbang/compose-action@v1.0.0
      with:
        # relative path to compose file
        compose-file: test.yml # optional, default is ./docker-compose.yml
        # additional options to pass to `docker-compose down` command
        # down-flags: # optional, default is 

#     - name: Docker Compose - Build
#       run: |
#         docker-compose -f test.yml up -d --build
        
    - name: Docker Compose - Test
      # Not working:
      # docker-compose -f test.yml exec -T django pytest
      # ValueError: Port could not be cast to integer value as '${POSTGRES_PORT}'
      #
      # Possibru relevant:
      # https://github.com/pydanny/cookiecutter-django/issues/2848
      run: |
        docker ps -a
        docker-compose -f test.yml run --rm django pytest

        


