name: Django CI

env:
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
  DATABASE_URL: postgres://${{ secrets.POSTGRES_USER}}:${{ secrets.POSTGRES_PASSWORD}}@${{ secrets.POSTGRES_HOST}}:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}
  USE_DOCKER: yes
  IPYTHONDIR: /app/.ipython
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Docker Compose Action
      uses: isbang/compose-action@v1.0.0
      with:
        compose-file: test.yml 
       
    - name: Docker Compose - Test
      run: |
        docker-compose -f test.yml run --rm django pytest


        


